'use strict';
const el = id => document.getElementById(id);
const SAVE = 'entrega-ate-sexta-v1';
let state, running = false, lastTick = 0, muted = false, audio, activeTab = 'client';
const fresh = () => ({remaining:240,tokens:6,fee:500,cost:0,changes:0,step:0,generated:false,giant:false,photos:true,cartBug:false,promo:false,reviewed:false,payment:false,pix:false,cart:0,version:0,previous:null,pendingAI:null,variant:Math.floor(Math.random()*2),done:false});
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE));if(s && s.remaining>0 && s.remaining<=240 && Number.isInteger(s.step) && s.step>=0 && s.step<=4 && s.tokens>=0 && s.tokens<=6 && typeof s.generated==='boolean' && !s.done)return s;}catch{}return null;}
function beep(){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=620;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.start();o.stop(audio.currentTime+.1);}catch{}}
function say(text,open=true){const reply=text.match(/Cliente: “([^”]+)”/);if(reply){state.pendingClientReply='“'+reply[1]+'”';text=text.replace(reply[0],'').trim()||'O cliente respondeu ao combinado.';}el('feedback').textContent=text;el('feedbackBubble').hidden=false;state.feedback=text;if(open)scheduleFit();beep();}
function decision(text){state.decision=text;}
function canAct(){if(running)return true;say('A partida está pausada. Clique em Continuar, no topo, para retomar.');return false;}
function ready(){return state.generated&&state.step===4&&!state.cartBug&&(state.payment||state.pix)&&(state.reviewed||(!state.giant&&state.photos));}
function updateObjective(){const pending=[];if(state.cartBug)pending.push('corrigir o carrinho');if(!state.payment&&!state.pix)pending.push('definir o pagamento');if(!state.reviewed&&!state.photos)pending.push('resolver as fotos');if(!state.reviewed&&state.giant)pending.push('resolver o tamanho do preço');el('objective').textContent=!running?'PARTIDA PAUSADA · clique em Continuar':state.pendingAI&&activeTab==='ai'?'PRÓXIMO PASSO · '+({price:'Aumentar preço',cart:'Corrigir carrinho',payment:'Corrigir pagamento',visual:'Restaurar visual anterior'}[state.pendingAI]||'confirme o pedido')+' na IA':!state.generated?'PRÓXIMO PASSO · gere a loja com a IA':ready()?'LOJA PRONTA · clique em Publicar e cobrar':state.step<4?'ETAPA '+state.step+' / 4 · '+({1:'responda ao pedido sobre o preço',2:'decida o que fazer com as duas canecas',3:'defina como a loja recebe pagamentos'}[state.step]):'ANTES DE ENTREGAR · '+pending.join(', ');el('objective').classList.toggle('ready',ready());el('publish').classList.toggle('ready-to-publish',ready());}

function snapshot(){state.previous={giant:state.giant,photos:state.photos,cartBug:state.cartBug,promo:state.promo,payment:state.payment,pix:state.pix};state.version++;}
function workspace(view){document.querySelector('.desktop').dataset.view=view;el('shopView').setAttribute('aria-pressed',String(view==='store'));el('chatView').setAttribute('aria-pressed',String(view==='chat'));scheduleFit();}
function tab(name){activeTab=name;el('clientPane').hidden=name!=='client';el('aiPane').hidden=name!=='ai';el('clientTab').setAttribute('aria-selected',String(name==='client'));el('aiTab').setAttribute('aria-selected',String(name==='ai'));workspace('chat');if(name==='ai')clientVoice.stop();if(name==='client'){el('unread').textContent='';if(state&&el('voiceNote'))clientVoice.mount(el('voiceNote'),({1:'shop',2:'mugs'})[state.step],running);}if(state)updateObjective();scheduleFit();}
function buttons(target,items){el(target).replaceChildren();items.forEach(([label,fn,disabled=false])=>{const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=()=>{if(!canAct())return;clientVoice.stop();if(target==='aiActions'&&label!=='Ver resposta do cliente'&&!b.classList.contains('suggested-correction'))state.pendingAI=null;decision(label);fn();if(!state.done){render();save();}};el(target).append(b);});}
function requestAI(task,prompt){rememberAI();state.pendingAI=task;state.aiRequest=prompt;state.aiReply='Pedido preparado. Clique em '+({price:'“Aumentar preço”',cart:'“Corrigir carrinho”',payment:'“Corrigir pagamento”',visual:'“Restaurar visual anterior”'}[task])+' para enviar à IA. Esse clique gasta um pedido.';el('aiRequest').textContent=prompt;el('aiRequestBubble').hidden=false;el('aiMessage').textContent=state.aiReply;tab('ai');}
function ai(label,change,message){if(!canAct())return;if(!state.tokens){say('Seus créditos acabaram. A IA mandou um link para o plano Pro.');return;}snapshot();state.tokens--;state.cost+=30;const prompt=state.pendingAI?state.aiRequest:state.decision||label;rememberAI();state.pendingAI=null;const previousStep=state.step;change();el('aiRequest').textContent=prompt;el('aiRequestBubble').hidden=false;el('aiMessage').textContent=message;state.aiRequest=el('aiRequest').textContent;state.aiReply=message;say(label,false);tab(!state.generated||state.step===previousStep?'ai':'client');}
function advance(){state.pendingAI=null;state.step++;state.changes++;el('unread').textContent='●';state.feedback='';el('feedbackBubble').hidden=true;}
function render(){el('tokens').textContent=state.tokens+' / 6';el('fee').textContent='R$ '+state.fee;el('version').textContent='v'+state.version;clock();el('test').disabled=!state.generated;el('publish').disabled=!state.generated;el('rollback').disabled=!state.previous;
if(!state.generated){el('store').innerHTML='<div class="empty-store"><strong>&lt;/&gt;</strong><p>Seu império ainda é uma pasta vazia.</p></div>';}
else{el('store').className=[state.giant?'giant-price':'',state.photos?'':'no-photos'].join(' ');el('store').innerHTML='<div class="fit-content"><div class="store-header"><h2>Loja do Seu Gil</h2><span>Desde hoje · tradição milenar</span></div><div class="products">'+[['☕','Caneca de reunião',29],['🧢','Boné de CEO',49],['🧦','Meia de unicórnio',19]].map(([icon,name,price])=>'<article class="product"><span class="product-icon" aria-hidden="true">'+icon+'</span><h3>'+name+'</h3><span class="price">R$ '+price+'</span><button class="buy" aria-label="Comprar '+name+'">Comprar</button></article>').join('')+'</div><div class="cart-line"><span>Carrinho: <b>'+state.cart+'</b> item(ns)</span><button id="checkout">'+(state.pix?'Pagar com Pix':'Finalizar compra')+'</button></div></div>';document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{if(!canAct())return;state.cart+=(state.cartBug||state.promo)?2:1;say(state.promo?'Promoção combinada: duas unidades pelo preço de uma.':state.cartBug?'Você comprou um. O carrinho entendeu dois. Visão de crescimento.':'Produto adicionado. Uma coisa funcionando. Aproveite.');render();save();});el('checkout').onclick=()=>{if(!canAct()){showCheckoutNotice(false,'Partida pausada','Clique em Continuar, no topo, para testar a compra.');return;}const empty=!state.cart;const success=!empty&&(state.payment||state.pix);showCheckoutNotice(success,empty?'Seu carrinho está vazio':state.payment?'Pagamento aprovado':state.pix?'Pix de teste pronto':'ERRO 402 · Pagamento não implementado',empty?'Adicione um produto antes de finalizar a compra.':state.payment?'Compra de teste concluída! Agora clique em Publicar e cobrar para entregar a loja. Nenhum dinheiro real foi cobrado.':state.pix?'Pix de teste aprovado. Agora clique em Publicar e cobrar para entregar a loja. O cliente vai conferir os pagamentos manualmente.':'Não foi possível concluir a compra. A IA criou o botão, mas esqueceu de implementar o pagamento.');};}
const messages=['“Preciso de uma lojinha. Foto, preço e comprar. R$ 500, entrega até sexta. É simples, né?”',state.variant?'“O preço está tímido. Faz ele GRITAR promoção. Mas com elegância.”':'“Gostei. Só aumenta bastante o preço na tela. Meu público esqueceu os óculos.”','“Cliquei em comprar UMA caneca e apareceram DUAS no carrinho. É defeito ou a segunda é de graça?”','“Agora falta pagar. Achei que o botão já vinha com dinheiro dentro.”',state.cartBug?'“Voltou a promoção involuntária: cliquei uma vez e veio dois de novo. Consegue corrigir?”':!state.payment&&!state.pix?'“O visual voltou, mas o pagamento sumiu. Minha esposa gostou; meu caixa, nem tanto. Arruma isso?”':state.reviewed?'“Fechado, vamos manter o combinado. Pode entregar a loja.”':!state.photos?'“Minha esposa gostou mais quando tinha foto dos produtos. Consegue colocar de volta?”':state.giant?'“Minha esposa perguntou por que o preço está maior que o produto. Consegue diminuir?”':'“Testei aqui e gostei! Agora publica a loja para a gente começar a vender.”'];rememberClient(messages[state.step]);el('clientMessage').textContent=messages[state.step];
const clientActions=[
[['Abrir a IA',()=>tab('ai')]],
[['Aceitar. É só aumentar.',()=>requestAI('price','Aumente o destaque do preço na loja. O cliente disse “bastante”, sem especificar o limite.')],['Combinar um limite',()=>{snapshot();state.remaining-=12;advance();state.cartBug=true;say('Você combinou manter o preço legível. Cliente: “Fechado. Mas fui testar o carrinho e apareceram duas canecas.”');}]],
[['Assumir “compre um, leve dois”',()=>{snapshot();state.fee-=100;state.cartBug=false;state.promo=true;advance();say('Cliente: “Fechado! A segunda caneca é por sua conta, né?” Promoção combinada: R$ 100 descontados do freela. O carrinho não está mais pendente.');}],['Pedir correção à IA',()=>requestAI('cart','Corrija o carrinho: um clique está adicionando duas canecas, e o cliente quer comprar só uma.')],['Corrigir manualmente · 35s',()=>{snapshot();state.remaining-=35;state.cartBug=false;state.promo=false;advance();say('Cliente: “Agora veio só uma. Perdi a promoção, mas ganhei confiança.”');}]],
[['Integrar pagamento com IA',()=>requestAI('payment','Corrija o pagamento: o botão Finalizar compra existe, mas a compra não é concluída.')],['Lançar com Pix · R$ 50 a menos',()=>{snapshot();state.pix=true;state.fee-=50;advance();say('Cliente: “Eu confiro cada Pix? Virei o financeiro da empresa antes de ter empresa.” R$ 50 descontados do freela.');}]],
[['Manter o combinado',()=>{state.remaining-=10;state.reviewed=true;state.pendingAI=null;say('Cliente: “Tá bom, vamos manter assim.”'+(state.cartBug||(!state.payment&&!state.pix)?' Ainda há pendências técnicas. Confira o próximo passo acima.':' Agora clique em Publicar e cobrar para entregar a loja.'));}],['Abrir a IA para ajustar',()=>requestAI('visual','Volte ao visual da primeira versão: fotos visíveis e preço legível. Preserve o carrinho e o pagamento que já funcionam.')]]
];
if(state.step===4){
if(state.cartBug)clientActions[4]=[['Pedir correção à IA',()=>requestAI('cart','O carrinho voltou a duplicar produtos depois da troca de versão. Corrija sem mexer no pagamento.')]];
else if(!state.payment&&!state.pix)clientActions[4]=[['Integrar pagamento com IA',()=>requestAI('payment','O pagamento parou depois de voltar uma versão. Corrija sem alterar o visual da loja.')]];
else if(state.reviewed||(!state.giant&&state.photos))clientActions[4]=[['Testar antes de entregar',()=>el('test').click()]];
}
buttons('clientActions',clientActions[state.step].map(([l,f])=>[l,f,!running]));
const actions=state.generated?[
['Aumentar preço · 1 pedido',()=>ai('Preço em destaque. Em MUITO destaque.',()=>{state.giant=true;state.cartBug=true;advance();},'Aumentei a visibilidade do preço em 900%. Aproveitei para otimizar o carrinho.'),state.step!==1||state.pendingAI!=='price','price'],
['Restaurar visual anterior · 1 pedido',()=>ai('Visual original recuperado, funções preservadas.',()=>{state.photos=true;state.giant=false;state.reviewed=false;},'Trouxe as fotos e o preço legível de volta. Mantive o carrinho e o pagamento. Viagem no tempo sem apagar o trabalho de hoje.'),state.step!==4||(!state.giant&&state.photos),'visual'],
['Restaurar fotos',()=>ai('Fotos recuperadas. Ninguém precisou de uma reunião.',()=>{state.photos=true;},'Restaurei as fotos e preservei o carrinho.'),state.photos,'photos'],
['Normalizar preço',()=>ai('O preço voltou a caber na loja.',()=>{state.giant=false;},'Reduzi o preço na tela. O valor do produto continua igual.'),!state.giant,'normalize'],
['Corrigir carrinho',()=>{const first=state.step===2;ai(first?'Carrinho corrigido. Fotos desaparecidas.':'Carrinho corrigido e revisado.',()=>{state.cartBug=false;state.promo=false;if(first){state.photos=false;advance();}},first?'Corrigi a duplicação. Removi as imagens para evitar distrações na compra.':'Cada clique agora adiciona um produto. Preservei o visual e o pagamento.');},!state.cartBug,'cart'],
['Corrigir pagamento · 1 pedido',()=>ai('Pagamento funcionando. Pode testar.',()=>{state.payment=true;if(state.step===3)advance();},'Integração concluída. Desta vez funcionou mesmo. Pode conferir.'),state.payment||state.pix||state.step<3,'payment']
]:[['Gerar a lojinha · 1 pedido',()=>ai('Loja gerada. Autoestima restaurada.',()=>{state.generated=true;state.step=1;},'Criei sua loja. Visual moderno, três produtos, carrinho e botão de pagamento. O botão existe. O pagamento ainda não.')]];
const relevant=actions.filter(([, ,resolved])=>!resolved).sort((a,b)=>Number(b[3]===state.pendingAI)-Number(a[3]===state.pendingAI));

buttons('aiActions',relevant.map(([l,f])=>[l,f,!running||(!state.tokens&&l!=='Ver resposta do cliente')]));
const selected=relevant.findIndex(a=>a[3]&&a[3]===state.pendingAI);if(selected>=0){const button=el('aiActions').children[selected];button.classList.add('suggested-correction');button.setAttribute('aria-describedby','aiMessage');}
el('storeStatus').textContent=state.generated?'PRÉVIA INTERATIVA · clique em Comprar e teste o pagamento':'Aguardando seu primeiro prompt.';clientVoice.mount(el('voiceNote'),({1:'shop',2:'mugs'})[state.step],running&&activeTab==='client');updateObjective();renderHistory();scheduleFit();}
function showCheckoutNotice(success,title,message){
  el('checkoutNotice')?.remove();
  const notice=document.createElement('div');
  notice.id='checkoutNotice';
  notice.className='checkout-notice '+(success?'checkout-success':'checkout-error');
  notice.setAttribute('role',success?'status':'alert');
  notice.tabIndex=-1;
  const heading=document.createElement('strong');heading.textContent=(success?'✓ ':'⚠ ')+title;
  const detail=document.createElement('p');detail.textContent=message;
  notice.append(heading,detail);
  el('store').querySelector('.cart-line').before(notice);
  notice.focus({preventScroll:true});
  const area=el('store'),box=area.getBoundingClientRect(),rect=notice.getBoundingClientRect();
  if(rect.top<box.top||rect.bottom>box.bottom)area.scrollTop+=rect.top-box.top-12;
  say(title+'. '+message);scheduleFit();
}
function clock(){const sec=Math.max(0,Math.ceil(state.remaining));el('clock').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');el('clock').classList.toggle('danger',sec<30);}
function start(s){clientVoice.reset();state=s;running=true;lastTick=performance.now();el('welcome').hidden=true;el('result').hidden=true;el('desk').hidden=false;el('pause').textContent='Pausar';el('aiMessage').textContent=state.aiReply||'Pode deixar comigo. O que poderia dar errado?';el('aiRequest').textContent=state.aiRequest||'';el('aiRequestBubble').hidden=!state.aiRequest;el('feedback').textContent=state.feedback||'';el('feedbackBubble').hidden=!state.feedback;tab(state.pendingAI?'ai':state.generated?'client':'ai');render();save();beep();}
function finish(timeout=false){clientVoice.stop();running=false;state.done=true;save();el('desk').hidden=true;el('result').hidden=false;const broken=state.cartBug||(!state.payment&&!state.pix);const good=!timeout&&!broken&&state.photos&&!state.giant;const title=timeout?'Sexta acabou. A loja não.':good?'Entrou no ar. E deu lucro.':'Sucesso com ressalvas.';const paid=timeout?0:broken?Math.round(state.fee*.5):state.fee;const profit=paid-state.cost;el('result').innerHTML='<div class="fit-content result-content"><span class="eyebrow">FREELA ENCERRADO · CLIENTE AINDA ONLINE</span><h2 class="result-title">'+title+'</h2><p>'+(timeout?'Você adiou a entrega. O cliente disse que entende. Mandou três áudios explicando que não entende.':good?'A loja funciona, o pagamento passa e as fotos continuam aqui. Você pode ir ao churrasco.':'A loja foi publicada. '+(state.cartBug?'Cada compra ainda vem em dobro. ':!state.payment&&!state.pix?'O pagamento ficou para a próxima versão. ':'')+(!state.photos?'As fotos estão de férias. ':'')+(state.giant?'O preço pode ser visto da estação espacial. ':''))+'</p><div class="receipt"><span>Recebeu</span><strong>R$ '+paid+'</strong><span>Gastou com IA</span><strong>R$ '+state.cost+'</strong><span>Saldo do freela</span><strong>R$ '+profit+'</strong><span>Alterações do cliente</span><strong>'+state.changes+'</strong></div><blockquote>“'+(good?'Para o próximo você faz um descontinho?':timeout?'Meu sobrinho começou aqui. Você consegue terminar o dele?':'Vou divulgar seu contato. Você resolve qualquer coisa, né?')+'”<cite>— Cliente satisfeito o suficiente para pedir mais</cite></blockquote><div id="resultVoice" class="voice-note"></div><div class="start-actions"><button class="primary" id="again">Outro freela. Agora eu sei.</button><a href="./">Voltar ao primeiro jogo</a></div></div>';scheduleFit();if(!timeout)clientVoice.mount(el('resultVoice'),'delivered');el('again').onclick=()=>start(fresh());el('result').querySelector('h2').tabIndex=-1;el('result').querySelector('h2').focus();beep();}
el('shopView').onclick=()=>workspace('store');el('chatView').onclick=()=>workspace('chat');
el('start').onclick=()=>start(fresh());const saved=load();if(saved){el('resume').hidden=false;el('resume').onclick=()=>start(saved);}
el('sound').onclick=()=>{muted=!muted;clientVoice.setMuted(muted);el('sound').textContent='Som: '+(muted?'desligado':'ligado');el('sound').setAttribute('aria-pressed',String(!muted));beep();};el('clientTab').onclick=()=>tab('client');el('aiTab').onclick=()=>tab('ai');[el('clientTab'),el('aiTab')].forEach(b=>b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const name=activeTab==='client'?'ai':'client';tab(name);el(name+'Tab').focus();}});
el('pause').onclick=()=>{clientVoice.stop();running=!running;lastTick=performance.now();el('pause').textContent=running?'Pausar':'Continuar';say(running?'De volta ao freela.':'Pausado. O cliente vai ter que esperar.');render();save();};
el('test').onclick=()=>{if(!canAct())return;decision('Testar a loja antes de entregar.');state.remaining-=8;say([state.promo?'OK: promoção combinada, duas unidades pelo preço de uma.':state.cartBug?'FALHOU: um clique adiciona dois produtos.':'OK: carrinho adiciona um produto.',state.payment?'OK: pagamento aprovado.':state.pix?'PIX: conferência manual combinada.':'FALHOU: pagamento não implementado.',state.photos?'OK: fotos visíveis.':'AVISO: fotos desapareceram.',state.giant?'AVISO: preço gigante.':'OK: preço legível.'].join(' '));clock();updateObjective();save();};el('rollback').onclick=()=>{if(!canAct()||!state.previous)return;decision('Voltar para a versão anterior.');const old=state.previous;const changes=[];for(const [key,value] of Object.entries(old)){if(state[key]!==value)changes.push(({giant:value?'o preço gigante voltou':'o preço ficou legível',photos:value?'as fotos voltaram':'as fotos sumiram',cartBug:value?'o carrinho voltou a duplicar':'o carrinho parou de duplicar',promo:value?'a promoção voltou':'a promoção saiu',payment:value?'o pagamento voltou':'o pagamento deixou de funcionar',pix:value?'o Pix voltou':'o Pix saiu'})[key]);}if(!changes.length){say('Cliente: “Essa versão está igual à outra. É o antes e depois de uma reforma que não aconteceu?” Nada mudou; nenhum tempo foi descontado.');render();save();return;}snapshot();Object.assign(state,old);state.reviewed=false;state.pendingAI=null;state.remaining-=12;say('Versão anterior restaurada: '+changes.join('; ')+'. Cliente: “Pedi para voltar o visual. Você trouxe o passado inteiro no pacote?”');render();save();};el('publish').onclick=()=>{if(canAct())finish();};
setInterval(()=>{const now=performance.now();if(running&&!clientVoice.playing){state.remaining-=Math.min((now-lastTick)/1000,2);clock();if(state.remaining<=0)finish(true);else save();}lastTick=now;},250);
document.addEventListener('visibilitychange',()=>{if(document.hidden)clientVoice.stop();if(document.hidden&&running){running=false;el('pause').textContent='Continuar';say('Pausado enquanto você estava fora.');render();save();}});

// Fit the current scene to its own panel, including the end screen.
let fitFrame;
function scheduleFit(){cancelAnimationFrame(fitFrame);fitFrame=requestAnimationFrame(fitScenes);}
function fitScenes(){document.querySelectorAll('#welcome,#result,#store,.chat-past').forEach(area=>{if(!area.getClientRects().length)return;const content=area.querySelector(':scope > .fit-content');if(!content)return;content.style.zoom='1';content.style.width='100%';const style=getComputedStyle(area);const availableWidth=area.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight);content.style.width=availableWidth+'px';const available=area.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom)-2;if(available<=0)return;if(area.closest('#clientPane')&&area.querySelector('.voice-note:not(:empty)')&&!area.classList.contains('history-visible')){fitVoiceTranscript(content,available);return;}let scale=1;for(let i=0;i<3;i++){const height=content.getBoundingClientRect().height;if(height<=available+1)break;scale*=available/height;content.style.zoom=String(scale);content.style.width=(availableWidth/scale)+'px';}});}
window.addEventListener('resize',scheduleFit);
if(window.ResizeObserver){const fitObserver=new ResizeObserver(scheduleFit);document.querySelectorAll('main,.desktop,.communication,.browser').forEach(area=>fitObserver.observe(area));}
scheduleFit();

function rememberClient(message){if(state.lastClient&&state.lastClient!==message){state.clientHistory??=[];state.clientHistory.push(state.lastClient);state.clientHistory=state.clientHistory.slice(-20);state.clientHistoryPage=null;state.clientShowHistory=false;}state.lastClient=message;if(state.pendingClientReply){state.clientHistory??=[];state.clientHistory.push(state.pendingClientReply);state.clientHistory=state.clientHistory.slice(-20);state.pendingClientReply=null;state.clientHistoryPage=null;}}
function rememberAI(){if(state.aiReply){state.aiHistory??=[];if(state.aiHistory.at(-1)!==state.aiReply)state.aiHistory.push(state.aiReply);state.aiHistory=state.aiHistory.slice(-20);state.aiHistoryPage=null;}}
function renderHistory(){['client','ai'].forEach(channel=>{const container=el(channel+'History');container.replaceChildren();const history=state[channel+'History']||[];if(!history.length)return;const index=Math.min(history.length-1,Math.max(0,state[channel+'HistoryPage']??history.length-1));const bubble=document.createElement('div');bubble.className='message previous-message';const label=document.createElement('small');label.textContent=channel==='client'?'CLIENTE · MENSAGEM ANTERIOR':'IA · RESPOSTA ANTERIOR';const p=document.createElement('p');p.textContent=history[index];bubble.append(label,p);container.append(bubble);if(channel==='client'&&el('voiceNote').children.length){const past=container.closest('.chat-past');past.classList.toggle('history-visible',!!state.clientShowHistory);const toggle=document.createElement('button');toggle.className='history-toggle';toggle.textContent=state.clientShowHistory?'Voltar ao áudio':'Mensagens anteriores';toggle.onclick=()=>{state.clientShowHistory=!state.clientShowHistory;renderHistory();scheduleFit();};container.prepend(toggle);}if(history.length>1){const nav=document.createElement('div');nav.className='history-navigation';for(const [label,delta] of [['← Anterior',-1],['Mais recente →',1]]){const button=document.createElement('button');button.textContent=label;button.disabled=index+delta<0||index+delta>=history.length;button.onclick=()=>{state[channel+'HistoryPage']=index+delta;renderHistory();scheduleFit();};nav.append(button);}container.append(nav);}});}

// Keep voice text readable; page the transcript when a short screen has less room.
function fitVoiceTranscript(content, available){
 const transcript=content.querySelector('.voice-transcript');if(!transcript)return;
 transcript.dataset.fullText??=transcript.textContent;
 const words=transcript.dataset.fullText.split(/\s+/);
 content.querySelector('.transcript-navigation')?.remove();
 transcript.textContent=transcript.dataset.fullText;
 if(content.getBoundingClientRect().height<=available+1)return;
 const nav=document.createElement('div');nav.className='transcript-navigation';
 const back=document.createElement('button'),next=document.createElement('button'),label=document.createElement('small');
 back.textContent='←';back.setAttribute('aria-label','Trecho anterior da transcrição');next.textContent='→';next.setAttribute('aria-label','Próximo trecho da transcrição');nav.append(back,label,next);transcript.after(nav);
 const pages=[];let start=0;
 while(start<words.length){let low=1,high=words.length-start,best=1;
 while(low<=high){const count=Math.floor((low+high)/2);transcript.textContent=words.slice(start,start+count).join(' ');if(content.getBoundingClientRect().height<=available+1){best=count;low=count+1;}else high=count-1;}
 pages.push(words.slice(start,start+best).join(' '));start+=best;
 }
 const page=Math.min(pages.length-1,Number(transcript.dataset.page)||0);transcript.textContent=pages[page];label.textContent=(page+1)+' / '+pages.length;back.disabled=page===0;next.disabled=page===pages.length-1;
 back.onclick=()=>{transcript.dataset.page=String(page-1);scheduleFit();};next.onclick=()=>{transcript.dataset.page=String(page+1);scheduleFit();};
}
