'use strict';
const el = id => document.getElementById(id);
const SAVE = 'entrega-ate-sexta-v1';
let state, running = false, lastTick = 0, muted = false, audio, activeTab = 'client';
const fresh = () => ({remaining:240,tokens:6,fee:500,cost:0,changes:0,step:0,generated:false,giant:false,photos:true,cartBug:false,payment:false,pix:false,cart:0,version:0,previous:null,variant:Math.floor(Math.random()*2),done:false});
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE));if(s && s.remaining>0 && s.remaining<=240 && Number.isInteger(s.step) && s.step>=0 && s.step<=4 && s.tokens>=0 && s.tokens<=6 && typeof s.generated==='boolean' && !s.done)return s;}catch{}return null;}
function beep(){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=620;g.gain.setValueAtTime(.03,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.start();o.stop(audio.currentTime+.1);}catch{}}
function say(text){el('feedback').textContent=text;beep();}
function snapshot(){state.previous={giant:state.giant,photos:state.photos,cartBug:state.cartBug,payment:state.payment,pix:state.pix};state.version++;}
function tab(name){activeTab=name;el('clientPane').hidden=name!=='client';el('aiPane').hidden=name!=='ai';el('clientTab').setAttribute('aria-selected',String(name==='client'));el('aiTab').setAttribute('aria-selected',String(name==='ai'));if(name==='client')el('unread').textContent='';}
function buttons(target,items){el(target).replaceChildren();items.forEach(([label,fn,disabled=false])=>{const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=()=>{clientVoice.stop();fn();if(!state.done){render();save();}};el(target).append(b);});}
function ai(label,change,message){if(!running)return;if(!state.tokens){say('Seus créditos acabaram. A IA mandou um link para o plano Pro.');return;}snapshot();state.tokens--;state.cost+=30;change();el('aiMessage').textContent=message;say(label);}
function advance(){state.step++;state.changes++;el('unread').textContent='●';tab('client');}
function render(){el('tokens').textContent=state.tokens+' / 6';el('fee').textContent='R$ '+state.fee;el('version').textContent='v'+state.version;clock();el('test').disabled=!state.generated;el('publish').disabled=!state.generated;el('rollback').disabled=!state.previous;
if(!state.generated){el('store').innerHTML='<div class="empty-store"><strong>&lt;/&gt;</strong><p>Seu império ainda é uma pasta vazia.</p></div>';}
else{el('store').className=[state.giant?'giant-price':'',state.photos?'':'no-photos'].join(' ');el('store').innerHTML='<div class="store-header"><h2>Loja do Seu Gil</h2><span>Desde hoje · tradição milenar</span></div><div class="products">'+[['☕','Caneca de reunião',29],['🧢','Boné de CEO',49],['🧦','Meia de unicórnio',19]].map(([icon,name,price])=>'<article class="product"><span class="product-icon" aria-hidden="true">'+icon+'</span><h3>'+name+'</h3><span class="price">R$ '+price+'</span><button class="buy" aria-label="Comprar '+name+'">Comprar</button></article>').join('')+'</div><div class="cart-line"><span>Carrinho: <b>'+state.cart+'</b> item(ns)</span><button id="checkout">'+(state.pix?'Pagar com Pix':'Finalizar compra')+'</button></div>';document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{if(!running)return;state.cart+=state.cartBug?2:1;say(state.cartBug?'Você comprou um. O carrinho entendeu dois. Visão de crescimento.':'Produto adicionado. Uma coisa funcionando. Aproveite.');render();save();});el('checkout').onclick=()=>{if(!running)return;const empty=!state.cart;const success=!empty&&(state.payment||state.pix);showCheckoutNotice(success,empty?'Seu carrinho está vazio':state.payment?'Pagamento aprovado':state.pix?'Pix de teste pronto':'ERRO 402 · Pagamento não implementado',empty?'Adicione um produto antes de finalizar a compra.':state.payment?'Compra de teste concluída. Nenhum dinheiro real foi cobrado.':state.pix?'O cliente vai conferir cada pagamento manualmente. Nenhum Pix real foi gerado.':'Não foi possível concluir a compra. A IA criou o botão, mas esqueceu de implementar o pagamento.');};}
const messages=['“Preciso de uma lojinha. Foto, preço e comprar. R$ 500, entrega até sexta. É simples, né?”',state.variant?'“O preço está tímido. Faz ele GRITAR promoção. Mas com elegância.”':'“Gostei. Só aumenta bastante o preço na tela. Meu público esqueceu os óculos.”','“Cliquei em comprar UMA caneca e apareceram DUAS no carrinho. É defeito ou a segunda é de graça?”','“Agora falta pagar. Achei que o botão já vinha com dinheiro dentro.”','“Minha esposa viu. Prefere a primeira versão. Mas com tudo que a gente adicionou.”'];el('clientMessage').textContent=messages[state.step];
const clientActions=[ [['Abrir a IA',()=>tab('ai')]], [['Aceitar. É só aumentar.',()=>{ai('Preço em destaque. Em MUITO destaque.',()=>{state.giant=true;state.cartBug=true;advance();},'Aumentei a visibilidade do preço em 900%. Aproveitei para otimizar o carrinho.');}],['Combinar um limite',()=>{state.remaining-=12;advance();state.cartBug=true;say('Preço legível, prazo protegido. O carrinho da primeira versão ainda precisa de teste.');}]], [['Assumir “compre um, leve dois”',()=>{state.fee-=100;advance();say('Promoção oficializada. O desconto saiu do seu pagamento.');}],['Pedir correção à IA',()=>{ai('Carrinho corrigido. Fotos desaparecidas.',()=>{state.cartBug=false;state.photos=false;advance();},'Corrigi a duplicação. Removi as imagens para evitar distrações na compra.');}],['Corrigir manualmente · 35s',()=>{snapshot();state.remaining-=35;state.cartBug=false;advance();say('Um clique, um produto. Seu sobrinho não mencionou essa parte.');}]], [['Integrar pagamento com IA',()=>{ai('Pagamento funcionando. Pode testar.',()=>{state.payment=true;advance();},'Integração concluída. Desta vez funcionou mesmo. Pode conferir.');}],['Lançar com Pix · R$ 50 a menos',()=>{snapshot();state.pix=true;state.fee-=50;advance();say('Entrega simplificada. O cliente ganhou o cargo de conferente de Pix.');}]], [['Manter o combinado',()=>{state.remaining-=10;say('Cliente: “Tá bom. Na próxima eu mostro pra ela antes.” Você já pode publicar.');}],['Abrir a IA para ajustar',()=>tab('ai')]] ];buttons('clientActions',clientActions[state.step].map(([l,f])=>[l,f,!running]));
const actions=state.generated?[['Restaurar fotos',()=>ai('Fotos recuperadas. Ninguém precisou de uma reunião.',()=>{state.photos=true;},'Restaurei as fotos e preservei o carrinho.'),state.photos],['Normalizar preço',()=>ai('O preço voltou a caber na loja.',()=>{state.giant=false;},'Reduzi o preço na tela. O valor do produto continua igual.'),!state.giant],['Corrigir carrinho',()=>ai('Carrinho corrigido e revisado.',()=>{state.cartBug=false;},'Cada clique agora adiciona um produto.'),!state.cartBug],['Integrar pagamento',()=>ai('Pagamento de teste pronto.',()=>{state.payment=true;},'Pagamento implementado. Teste antes de publicar.'),state.payment]]:[['Gerar a lojinha · 1 pedido',()=>{ai('Loja gerada. Autoestima restaurada.',()=>{state.generated=true;state.step=1;},'Criei sua loja. Visual moderno, três produtos, carrinho e botão de pagamento. O botão existe. O pagamento ainda não.');tab('client');}]];buttons('aiActions',actions.map(([l,f,d])=>[l,f,d||!running||!state.tokens]));el('storeStatus').textContent=state.generated?'PRÉVIA INTERATIVA · clique em Comprar e teste o pagamento':'Aguardando seu primeiro prompt.';clientVoice.mount(el('voiceNote'),({1:'shop',2:'mugs'})[state.step],running);}
function showCheckoutNotice(success,title,message){
  el('checkoutNotice')?.remove();
  const notice=document.createElement('div');
  notice.id='checkoutNotice';
  notice.className='checkout-notice '+(success?'checkout-success':'checkout-error');
  notice.setAttribute('role',success?'status':'alert');
  notice.tabIndex=-1;
  const heading=document.createElement('strong');heading.textContent=(success?'✓ ':'⚠ ')+title;
  const detail=document.createElement('p');detail.textContent=message;
  notice.append(heading,detail);
  el('store').querySelector('.cart-line').before(notice);
  notice.focus({preventScroll:true});
  const area=el('store'),box=area.getBoundingClientRect(),rect=notice.getBoundingClientRect();
  if(rect.top<box.top||rect.bottom>box.bottom)area.scrollTop+=rect.top-box.top-12;
  say(title+'. '+message);
}
function clock(){const sec=Math.max(0,Math.ceil(state.remaining));el('clock').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');el('clock').classList.toggle('danger',sec<30);}
function start(s){clientVoice.reset();state=s;running=true;lastTick=performance.now();el('welcome').hidden=true;el('result').hidden=true;el('desk').hidden=false;el('pause').textContent='Pausar';el('aiMessage').textContent='Pode deixar comigo. O que poderia dar errado?';tab(state.generated?'client':'ai');render();save();beep();}
function finish(timeout=false){clientVoice.stop();running=false;state.done=true;save();el('desk').hidden=true;el('result').hidden=false;const broken=state.cartBug||(!state.payment&&!state.pix);const good=!timeout&&!broken&&state.photos&&!state.giant;const title=timeout?'Sexta acabou. A loja não.':good?'Entrou no ar. E deu lucro.':'Sucesso com ressalvas.';const paid=timeout?0:broken?Math.round(state.fee*.5):state.fee;const profit=paid-state.cost;el('result').innerHTML='<span class="eyebrow">FREELA ENCERRADO · CLIENTE AINDA ONLINE</span><h2 class="result-title">'+title+'</h2><p>'+(timeout?'Você adiou a entrega. O cliente disse que entende. Mandou três áudios explicando que não entende.':good?'A loja funciona, o pagamento passa e as fotos continuam aqui. Você pode ir ao churrasco.':'A loja foi publicada. '+(state.cartBug?'Cada compra ainda vem em dobro. ':!state.payment&&!state.pix?'O pagamento ficou para a próxima versão. ':'')+(!state.photos?'As fotos estão de férias. ':'')+(state.giant?'O preço pode ser visto da estação espacial. ':''))+'</p><div class="receipt"><span>Recebeu</span><strong>R$ '+paid+'</strong><span>Gastou com IA</span><strong>R$ '+state.cost+'</strong><span>Saldo do freela</span><strong>R$ '+profit+'</strong><span>Alterações do cliente</span><strong>'+state.changes+'</strong></div><blockquote>“'+(good?'Para o próximo você faz um descontinho?':timeout?'Meu sobrinho começou aqui. Você consegue terminar o dele?':'Vou divulgar seu contato. Você resolve qualquer coisa, né?')+'”<cite>— Cliente satisfeito o suficiente para pedir mais</cite></blockquote><div id="resultVoice" class="voice-note"></div><div class="start-actions"><button class="primary" id="again">Outro freela. Agora eu sei.</button><a href="./">Voltar ao primeiro jogo</a></div>';if(!timeout)clientVoice.mount(el('resultVoice'),'delivered');el('again').onclick=()=>start(fresh());el('result').querySelector('h2').tabIndex=-1;el('result').querySelector('h2').focus();beep();}
el('start').onclick=()=>start(fresh());const saved=load();if(saved){el('resume').hidden=false;el('resume').onclick=()=>start(saved);}
el('sound').onclick=()=>{muted=!muted;clientVoice.setMuted(muted);el('sound').textContent='Som: '+(muted?'desligado':'ligado');el('sound').setAttribute('aria-pressed',String(!muted));beep();};el('clientTab').onclick=()=>tab('client');el('aiTab').onclick=()=>tab('ai');[el('clientTab'),el('aiTab')].forEach(b=>b.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const name=activeTab==='client'?'ai':'client';tab(name);el(name+'Tab').focus();}});
el('pause').onclick=()=>{clientVoice.stop();running=!running;lastTick=performance.now();el('pause').textContent=running?'Pausar':'Continuar';say(running?'De volta ao freela.':'Pausado. O cliente vai ter que esperar.');render();save();};
el('test').onclick=()=>{if(!running)return;state.remaining-=8;say([state.cartBug?'FALHOU: um clique adiciona dois produtos.':'OK: carrinho adiciona um produto.',state.payment?'OK: pagamento aprovado.':state.pix?'PIX: conferência manual combinada.':'FALHOU: pagamento não implementado.',state.photos?'OK: fotos visíveis.':'AVISO: fotos desapareceram.',state.giant?'AVISO: preço gigante.':'OK: preço legível.'].join(' '));clock();save();};el('rollback').onclick=()=>{if(!running||!state.previous)return;const old=state.previous;snapshot();Object.assign(state,old);state.remaining-=12;say('Versão anterior restaurada. Confira o que voltou junto.');render();save();};el('publish').onclick=()=>{if(running)finish();};
setInterval(()=>{const now=performance.now();if(running&&!clientVoice.playing){state.remaining-=Math.min((now-lastTick)/1000,2);clock();if(state.remaining<=0)finish(true);else save();}lastTick=now;},250);
document.addEventListener('visibilitychange',()=>{if(document.hidden)clientVoice.stop();if(document.hidden&&running){running=false;el('pause').textContent='Continuar';say('Pausado enquanto você estava fora.');render();save();}});
